steps:
- id: 'pipeline stage 1'
  name: 'alpine'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "hello testing"
      echo "***********************"

- id: 'simple-stage 2'
  name: 'alpine'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      echo "This is a simple stage."
      echo "You can add more commands here."
      echo "***********************"

options:
  logging: CLOUD_LOGGING_ONLY
