steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "hello testing"
      echo "***********************"
options:
  logging: CLOUD_LOGGING_ONLY
